name: Laravel Deploy to AWS
on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
      - name: Create .env file
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # - name: Run Tests
      #   env:
      #     DB_CONNECTION: mysql
      #     DB_HOST: ${{ env.DB_HOST }}
      #     DB_PORT: ${{ env.DB_PORT }}
      #     DB_DATABASE: ${{ env.DB_DATABASE }}
      #     DB_USERNAME: ${{ env.DB_USERNAME }}
      #     DB_PASSWORD: ${{ env.DB_PASSWORD }}
      #   run: php artisan test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            echo "DB_CONNECTION=mysql" >> .env
            echo "DB_HOST=${{ env.DB_HOST }}" >> .env
            echo "DB_PORT=${{ env.DB_PORT }}" >> .env
            echo "DB_DATABASE=${{ env.DB_DATABASE }}" >> .env
            echo "DB_USERNAME=${{ env.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart apache2
